const casas = [
  {
    id: 1,
    habitaciones: 4,
    tamano: 200,
    localidad: "Caracas",
    precio: 150000,
  },
  {
    id: 2,
    habitaciones: 2,
    tamano: 75,
    localidad: "Caracas",
    precio: 80000,
  },
  {
    id: 3,
    habitaciones: 3,
    tamano: 100,
    localidad: "Caracas",
    precio: 80000,
  },
  {
    id: 4,
    habitaciones: 3,
    tamano: 110,
    localidad: "Valencia",
    precio: 85000,
  },
  {
    id: 5,
    habitaciones: 3,
    tamano: 110,
    localidad: "Valencia",
    precio: 85000,
  },
  {
    id: 6,
    habitaciones: 3,
    tamano: 110,
    localidad: "Valencia",
    precio: 85000,
  },
  {
    id: 7,
    habitaciones: 2,
    tamano: 60,
    localidad: "La Guaira",
    precio: 40000,
  },
  {
    id: 8,
    habitaciones: 4,
    tamano: 200,
    localidad: "La Guaira",
    precio: 140000,
  },
  {
    id: 9,
    habitaciones: 2,
    tamano: 60,
    localidad: "La Guaira",
    precio: 40000,
  },
  {
    id: 10,
    habitaciones: 4,
    tamano: 120,
    localidad: "El Tigre",
    precio: 80000,
  },
  {
    id: 11,
    habitaciones: 3,
    tamano: 130,
    localidad: "El Tigre",
    precio: 90000,
  },
  {
    id: 12,
    habitaciones: 2,
    tamano: 87,
    localidad: "El Tigre",
    precio: 60000,
  },
  {
    id: 13,
    habitaciones: 3,
    tamano: 95,
    localidad: "Tinaquillo",
    precio: 120000,
  },
  {
    id: 14,
    habitaciones: 2,
    tamano: 150,
    localidad: "Tinaquillo",
    precio: 130000,
  },
  {
    id: 15,
    habitaciones: 1,
    tamano: 45,
    localidad: "Tinaquillo",
    precio: 10000,
  },
  {
    id: 16,
    habitaciones: 3,
    tamano: 75,
    localidad: "Tucaní",
    precio: 100000,
  },
  {
    id: 17,
    habitaciones: 3,
    tamano: 95,
    localidad: "Tucaní",
    precio: 120000,
  },
  {
    id: 18,
    habitaciones: 3,
    tamano: 110,
    localidad: "Tucaní",
    precio: 130000,
  },
  {
    id: 19,
    habitaciones: 2,
    tamano: 60,
    localidad: "Puerto Cabello",
    precio: 30000,
  },
  {
    id: 20,
    habitaciones: 3,
    tamano: 120,
    localidad: "Puerto Cabello",
    precio: 130000,
  },
  {
    id: 21,
    habitaciones: 1,
    tamano: 40,
    localidad: "Puerto Cabello",
    precio: 20000,
  },
  {
    id: 22,
    habitaciones: 3,
    tamano: 70,
    localidad: "Puerto Cabello",
    precio: 90000,
  },
];
